# Generated by Django 5.0.8 on 2024-09-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event_remove_task_admin_delete_adminavailability_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
