# Generated by Django 5.0.8 on 2024-09-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_appointment_time_slot_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
