# Generated by Django 5.0.8 on 2024-09-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='title',
        ),
    ]
