# Generated by Django 5.0.8 on 2024-09-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_name_events_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
