# Generated by Django 5.0.8 on 2024-09-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_events_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_booked',
            field=models.BooleanField(default=True),
        ),
    ]
