# Generated by Django 5.0.8 on 2024-09-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_events_is_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='is_booked',
        ),
    ]
