# Generated by Django 5.1.5 on 2025-01-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_meeting_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
