# Generated by Django 5.1.5 on 2025-01-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_meetingnotification_invitee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingNotification',
        ),
    ]
