# Generated by Django 5.1.5 on 2025-02-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_invitation_decline_reason_invitation_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingNotification',
        ),
    ]
