# Generated by Django 5.1.5 on 2025-02-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
